# MariaDB 데이터베이스 연결 설정
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jeja?useSSL=false&allowPublicKeyRetrieval=true
    username: jejauser
    password: 0000
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  # Thymeleaf 설정
  thymeleaf:
    cache: false

# 서버 설정
server:
  port: 8080
