# MariaDB 데이터베이스 연결 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeja?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: Ddgh93081)
    driver-class-name: com.mysql.cj.jdbc.Driver

    # JPA 설정
    jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Thymeleaf 설정
  thymeleaf:
    cache: false

# 서버 설정
server:
  address: 0.0.0.0
  port: 8080
