# MySQL 데이터베이스 연결 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeja?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ddgh930810
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Thymeleaf 설정
  thymeleaf:
    cache: false

# 서버 설정
server:
  port: 8080
